server:
  port: 8888

spring:
  # 配置数据源信息p
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mrs?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  mail:
    # 发送邮件服务器
    host: smtp.qq.com
    # 发送邮件的用户名
    username: xxx@qq.com
    # 发送邮件的授权码
    password: mwdtcymfstbubiii
    # 编码格式
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtp
    # 发送邮件的地址
    from: xxx@qq.com
    properties.mail.smtp.port: 465
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true


# 配置MyBatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: cn.zjw.mrs.enums

aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-shanghai.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: 
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: 
    # oss的存储空间
    bucketName: qgys
    # 上传文件大小(M)
    maxSize: 3
    # 上传文件夹路径前缀
    dir:
      prefix: recommend/avatar/